// this file is generated by virmator for code coverage calculations in the test-web command
import * as import0 from './source-file';

// this is just here to make sure the imports don't get removed for not being used
const allImports = {
    import0,
};
