import {
    baseAllowedRecentDeps,
    RecentDepsAllowList,
} from '@virmator/deps/configs/deps-regen.config.base.js';

/**
 * Allowlist of npm packages whose `node_modules` and lockfile entries should be regenerated by
 * `virmator deps regen`. Each entry is either an npm package name (e.g. `'react'`, `'@scope/foo'`)
 * or an npm author handle (e.g. `'electrovir'`); anything published by an allowlisted author is
 * also regenerated. Anything not matching this list is left alone.
 */
export const depsRegenAllowList: RecentDepsAllowList = [
    ...baseAllowedRecentDeps,
];
