name: tests

on:
    push:
        branches:
            - '**'

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
        steps:
            - uses: actions/checkout@v4.1.7
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4.0.3
              with:
                  node-version-file: '.nvmrc'
            - name: run test
              run: |
                  npm ci
                  npm run test:all
