name: 'tagged-release'

on:
    push:
        tags:
            - 'v*'

jobs:
    tagged-release:
        name: 'Tagged Release'
        runs-on: 'ubuntu-latest'

        steps:
            - name: 'build and test'
              run: |
                  npm ci
                  npm run test:full

            - uses: 'marvinpinto/action-automatic-releases@latest'
              with:
                  repo_token: '${{ secrets.GITHUB_TOKEN }}'
                  prerelease: false
